//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yad2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add
    {
        public Add()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int id { get; set; }
        public System.DateTime DatePublished { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string About { get; set; }
        public string CategoryType { get; set; }
        public string LocationArea { get; set; }
        public string PartnerEmail { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Location Location { get; set; }
        public virtual Group Group { get; set; }
        public virtual Partner Advertisor { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
    }
}
