//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yad2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Partners = new HashSet<Partner>();
        }
    
        public int Id { get; set; }
        public string ManagerEmail { get; set; }
        public string CategoryType { get; set; }
        public string Chat { get; set; }
    
        public virtual Add Add { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual ICollection<Partner> Partners { get; set; }
        public virtual Category Category { get; set; }
    }
}
