//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yad2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.UsersInMessage = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Date { get; set; }
        public string Content { get; set; }
        public string UserEmail { get; set; }
    
        public virtual User Creator { get; set; }
        public virtual ICollection<User> UsersInMessage { get; set; }
    }
}
