//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yad2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner : User
    {
        public Partner()
        {
            this.PartnerIn = new HashSet<Group>();
            this.AddsAdvertized = new HashSet<Add>();
            this.RequestsRecived = new HashSet<Request>();
        }
    
    
        public virtual ICollection<Group> PartnerIn { get; set; }
        public virtual ICollection<Add> AddsAdvertized { get; set; }
        public virtual ICollection<Request> RequestsRecived { get; set; }
    }
}
