//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yad2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public bool status { get; set; }
        public Nullable<int> Rank { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Add Add { get; set; }
        public virtual User User { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
