//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yad2
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.MessagesCreate = new HashSet<Message>();
            this.MessagesRecived = new HashSet<Message>();
            this.RequestsSent = new HashSet<Request>();
        }
    
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public bool Gender { get; set; }
    
        public virtual ICollection<Message> MessagesCreate { get; set; }
        public virtual ICollection<Message> MessagesRecived { get; set; }
        public virtual ICollection<Request> RequestsSent { get; set; }
    }
}
